/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as IssuesIdImport } from './routes/issues/$id'
import { Route as IssuesIndexImport } from './routes/issues/index'
import { Route as ListImport } from './routes/list'

// Create/Update Routes

const ListRoute = ListImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const IssuesIndexRoute = IssuesIndexImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRoute,
} as any)

const IssuesIdRoute = IssuesIdImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListImport
      parentRoute: typeof rootRoute
    }
    '/issues/$id': {
      id: '/issues/$id'
      path: '/issues/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof IssuesIdImport
      parentRoute: typeof rootRoute
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/list': typeof ListRoute
  '/issues/$id': typeof IssuesIdRoute
  '/issues': typeof IssuesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/list': typeof ListRoute
  '/issues/$id': typeof IssuesIdRoute
  '/issues': typeof IssuesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/list': typeof ListRoute
  '/issues/$id': typeof IssuesIdRoute
  '/issues/': typeof IssuesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/list' | '/issues/$id' | '/issues'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/list' | '/issues/$id' | '/issues'
  id: '__root__' | '/' | '/list' | '/issues/$id' | '/issues/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListRoute: typeof ListRoute
  IssuesIdRoute: typeof IssuesIdRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListRoute: ListRoute,
  IssuesIdRoute: IssuesIdRoute,
  IssuesIndexRoute: IssuesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/list",
        "/issues/$id",
        "/issues/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/list": {
      "filePath": "list.tsx"
    },
    "/issues/$id": {
      "filePath": "issues/$id.tsx"
    },
    "/issues/": {
      "filePath": "issues/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
